### ISSUE TITLE
Ошибка регистрации

### ISSUE THREAD

**Issue by yakovkurochkin** [clubadm/clubadm#2]
Ошибка не отображается, падает только в консоль браузера
Win 10, Google Chrome 47.0.2526.106

**Comment by kafeman** [comment]
Если вы про АДМ на Geektimes, то он еще не дописан просто. Будет как в Хабраверсии, все ошибочные сценарии обрабатываются в HTML через ng-if. Сервер отвечает ошибкой только на случай, если кто-то решит обойти проверку.
