### ISSUE TITLE
Не проходит регистрация. Текст ошибки: "Вы не можете участвовать в Клубе АДМ."

### ISSUE THREAD

**Issue by cianos** [clubadm/clubadm#3]
Мне не ясно почему это происходит. 
Имею статус RO на geektimes.ru

**Comment by kafeman** [comment]
ReadOnly участвовать не могут: https://github.com/clubadm/clubadm/blob/e17481c51654c09127ce76239c7837083195dfc6/clubadm/models.py#L129
